// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class CustomerService
    {
        public int QuestionId { get; set; }
        public DateTime QuestionDatetime { get; set; }
        public string QuestionKeynote { get; set; }
        public string QuestionContent { get; set; }
        public string Email { get; set; }
        public int EmployeeId { get; set; }
        public string AnswerContent { get; set; }
        public DateTime AnswerDatetime { get; set; }
    }
}