// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class Levels
    {
        public Levels()
        {
            Members = new HashSet<Members>();
        }

        public string LevelName { get; set; }
        public double DiscountRate { get; set; }

        public virtual ICollection<Members> Members { get; set; }
    }
}