// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class MemberLogin
    {
        public int MemberId { get; set; }
        public byte[] Account { get; set; }
        public byte[] Password { get; set; }

        public virtual Members Member { get; set; }
    }
}