// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class Members
    {
        public Members()
        {
            MemberPoints = new HashSet<MemberPoints>();
            Orders = new HashSet<Orders>();
        }

        public int MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public DateTime Birthday { get; set; }
        public DateTime RegisterDay { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string LevelName { get; set; }

        public virtual MemberLogin MemberLogin { get; set; }
        public virtual ICollection<MemberPoints> MemberPoints { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}