// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class MemberPoints
    {
        public MemberPoints()
        {
            MemberLevel = new HashSet<MemberLevel>();
        }

        public int PointsId { get; set; }
        public int MemberId { get; set; }
        public int AccumulatedPoints { get; set; }
        public DateTime GetDate { get; set; }
        public DateTime ExpirationDate { get; set; }

        public virtual Members Member { get; set; }
        public virtual ICollection<MemberLevel> MemberLevel { get; set; }
    }
}