// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class MemberLevel
    {
        public int MemberId { get; set; }
        public string LevelName { get; set; }
        public int PointsId { get; set; }

        public virtual Levels LevelNameNavigation { get; set; }
        public virtual MemberPoints Points { get; set; }
    }
}