// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EnjoyEat.Areas.OrderForHere.Models
{
    public partial class Reservation
    {
        public string PhoneNumber { get; set; }
        public DateTime? ReservationDate { get; set; }
        public DateTime? ConfirmationDate { get; set; }
        public string NumberofGuest { get; set; }
        public DateTime? ReservationTime { get; set; }

        public virtual ReservationInformation ReservationInformation { get; set; }
    }
}